### ISSUE TITLE
Link to Linux kernel

### ISSUE THREAD

**Issue by vanrein** [treitmayr/yealink-module#2]
This module has seen a lot of work relative to the one I found in my 5.15.0 kernel.

 1. Have you tried to update the kernel module?
 2. Is there DKMS support?
 3. Could you give out-of-source build instructions?

I played with under kernel version 5.15.0, and it fails with my Tiptel 115 on this kernel, using audio, libevdev, echo/cat:

  * audio works
  * LCD and LED are irresponsive
  * key events are dropping randomly from libevdev, even through the device does not show up as HID
 
I would love to try this updated module, but not if it means building the complete kernel for it.

**Comment by treitmayr** [comment]
Have you tried to compile just the kernel module (simply by running `make`)? That should actually work for kernel versions < 5.19.0. If not, please post the error output and the Linux system you are using.

BTW, I just updated the code to also support kernel versions up to 6.1, but that should not affect you.

**Comment by vanrein** [comment]
> Have you tried to compile just the kernel module (simply by running `make`)? That should actually work for kernel versions < 5.19.0. If not, please post the error output and the Linux system you are using.

Thanks for responding!  I had trouble with that, apparently it is worth the effort to fix it.  Probably local.  The ability to actually do this would be useful to add in the documentation anyway.  Will report back.

> BTW, I just updated the code to also support kernel versions up to 6.1, but that should not affect you.

Wonderful, thanks.

**Comment by treitmayr** [comment]
I now added DKMS support, see https://github.com/treitmayr/yealink-module/blob/master/README.md#compilation . Please give it a try and let me know if something does not work as it should, as this is my first `dkms.conf` I created.

**Comment by vanrein** [comment]
Thanks for a *big* improvement in module usability and documentation!

My testing was a bit more thorough than your standard run; after `dkms add` (worked) my `dkms build` needed headers.  I was still running on an Ubuntu kernel (had done a `dist-upgrade` from Ubuntu to Debian) so needed to update the kernel to 5.19.0.  It built while doing that, and installed it.  Good `dkms status`, both before and after reboot.

Check if it is there...
```
shell$ find /lib/modules/$(uname -r) -name yealink.ko
/lib/modules/5.19.0-0.deb11.2-amd64/extra/yealink.ko
```

The original has been removed (path below not found above)...
```
shell$ dpkg -L linux-image-$(uname -r) | grep yealink
/lib/modules/5.19.0-0.deb11.2-amd64/kernel/drivers/input/misc/yealink.ko
```

The module should plug/unplug...
```
shell$ lsmod | grep yealink
#indeed, silence
```

Tested modprobe and modprobe -r, both work as they should.

Now, some first-person idiot cleaned up the house, and misplaced the Tiptel 115 phone...  **this issue is closed with great thanks**, but I have a hardware problem to solve.  Will send a post-closing comment here.

*Law of Dissipation of Matter:* The likelihood of physical manifestation of hardware devices is inversely proportional to the amount of such devices; the dissipation may spontaneously ensue during cleanup activities.

**Comment by vanrein** [comment]
Found it.  Been looking for a white phone, turns out it was black :-S

The driver works, unlike the one shipped in the current kernel.  Certainly worthwhile replacing that one :-)

A few remarks:

  * The `#` key reports as `KEY_LEFTSHIFT`, whereas `*` does report as `KEY_KPASTERISK`
  * The README instruction `dkms status` does not require `sudo` (but it may need `/usr/sbin` in its path).  After having run the rest under `sudo` it hardly matters, of course.

Thanks, now I can go ahead and link this to BareSIP.  I already have shell commands for doing that, so it should be easy now.

**Comment by vanrein** [comment]
The phone works *directly* on the BareSIP commandline.  That includes the `#` key which is entered as te expected key value.  Backspace, Enter and Esc are all the right mappings for BareSIP.

**Comment by treitmayr** [comment]
That sounds great!
I knew BareSIP back when Alfred E. Heggestad started the project, but did not know it came along that far. Now what's probably missing in your setup is display output. In my old yeaphone (which used linphone as a library back then) I even implemented number memory :-) but have not used the handset for many years now.
The `#` key is actually [implemented](https://github.com/treitmayr/yealink-module/blob/5ed69fd3285b4762abf98fb65bb6f589f3abf4ea/yealink.c#L469) as left-shift + `3` so that's why it resulted in the correct key in BareSIP.
Have fun.
